"""
Document Compiler — transforms structured JSON section outputs into
a cohesive narrative business plan document.

Called by Mother Agent after all sections complete and coherence audit passes.
Produces a Markdown document that can be rendered to PDF.
"""

import json
import logging
import os
from typing import Optional

from agents.phase2.base_child_agent import get_shared_bedrock_client

from agents.phase2.llm_utils import strip_markdown_json

logger = logging.getLogger(__name__)

SECTION_ORDER = ["executive_summary", "1", "3", "4", "5", "8", "10", "12", "13"]

SECTION_TITLES = {
    "executive_summary": "Executive Summary",
    "1": "The Opportunity",
    "3": "External Environment",
    "4": "Organisation & Team",
    "5": "SWOT Analysis",
    "8": "Marketing Strategy",
    "10": "Operations",
    "12": "Financial Plan",
    "13": "Launch Programme & Contingency",
}


class DocumentCompiler:
    """Compiles JSON section outputs into narrative Markdown."""

    def __init__(self, bedrock_client=None, model_id: str = ""):
        self.bedrock = bedrock_client or get_shared_bedrock_client()
        self.model_id = model_id or os.getenv("CLAUDE_SONNET_MODEL", "claude-sonnet-4-20250514")

    async def compile(
        self,
        all_outputs: dict,
        business_name: str = "The Business",
        coherence_audit: Optional[dict] = None,
        council_reports: Optional[list] = None,
    ) -> str:
        """Compile all section outputs into a full Markdown business plan."""
        sections_md = []

        sections_md.append(f"# Business Plan: {business_name}\n")
        sections_md.append(f"*Generated by Multi-Agent AI System*\n")
        sections_md.append("---\n")

        for sec_num in SECTION_ORDER:
            output = all_outputs.get(sec_num)
            if not output or not isinstance(output, dict):
                continue

            title = SECTION_TITLES.get(sec_num, f"Section {sec_num}")
            section_md = await self._compile_section(sec_num, title, output)
            if section_md:
                sections_md.append(section_md)

        # Appendix: assumptions registry
        assumptions_md = self._compile_assumptions_appendix(all_outputs)
        if assumptions_md:
            sections_md.append(assumptions_md)

        # Appendix: confidence & data quality
        quality_md = self._compile_quality_appendix(all_outputs, coherence_audit)
        sections_md.append(quality_md)

        # Appendix: Council quality assurance
        if council_reports:
            council_md = self._compile_council_appendix(council_reports)
            sections_md.append(council_md)

        return "\n\n".join(sections_md)

    async def _compile_section(self, sec_num: str, title: str, output: dict) -> Optional[str]:
        """Transform a single section's JSON into narrative Markdown."""
        filtered = {k: v for k, v in output.items()
                    if k not in ("input_tokens", "output_tokens", "model_used", "task_id",
                                 "section_number", "reasoning_trace", "_da_verdict",
                                 "_da_challenges", "_da_recalibrated", "_constitution_warnings",
                                 "_coherence_feedback")}

        output_str = json.dumps(filtered, indent=2, default=str)[:8000]

        prompt = f"""Convert this structured business plan section into professional narrative prose.

SECTION: {title}

STRUCTURED DATA:
{output_str}

Rules:
- Write in third person, professional tone suitable for investors
- Use bullet points for lists of 3+ items
- Include specific numbers and metrics — never vague language
- Use Markdown formatting (## for subsections, **bold** for key terms, tables where appropriate)
- Keep it concise — 200-600 words per section
- If confidence is "low", note that this section requires further validation
- Do NOT include raw JSON or field names — transform them into natural language

Return ONLY the Markdown content for this section (no code blocks wrapping it)."""

        try:
            response = self.bedrock.converse(
                modelId=self.model_id,
                system=[{"text": "You are a professional business plan writer. Transform structured data into compelling, investor-ready prose. Use Markdown formatting."}],
                messages=[{"role": "user", "content": [{"text": prompt}]}],
                inferenceConfig={"maxTokens": 2048},
            )
            text = response["output"]["message"]["content"][0]["text"]
            return f"## {title}\n\n{text}"
        except Exception as e:
            logger.error("[DocumentCompiler] LLM failed for section %s: %s", sec_num, e)
            return self._fallback_section(title, output)

    def _fallback_section(self, title: str, output: dict) -> str:
        """Simple key-value rendering when LLM is unavailable."""
        lines = [f"## {title}\n"]
        for key, value in output.items():
            if key.startswith("_") or key in ("input_tokens", "output_tokens", "model_used", "task_id", "section_number"):
                continue
            display_key = key.replace("_", " ").title()
            if isinstance(value, str) and len(value) > 20:
                lines.append(f"**{display_key}:** {value}\n")
            elif isinstance(value, list):
                lines.append(f"**{display_key}:**\n")
                for item in value[:10]:
                    if isinstance(item, dict):
                        summary = ", ".join(f"{k}: {v}" for k, v in list(item.items())[:3])
                        lines.append(f"- {summary}")
                    else:
                        lines.append(f"- {item}")
                lines.append("")
            elif isinstance(value, dict):
                lines.append(f"**{display_key}:**\n")
                for k, v in list(value.items())[:8]:
                    lines.append(f"- {k}: {v}")
                lines.append("")
        return "\n".join(lines)

    def _compile_assumptions_appendix(self, all_outputs: dict) -> str:
        """Compile all assumptions into a single appendix table."""
        all_assumptions = []
        for sec_num, output in all_outputs.items():
            if not isinstance(output, dict):
                continue
            assumptions = output.get("assumptions_used", output.get("assumption_log", []))
            for a in assumptions:
                if isinstance(a, dict):
                    all_assumptions.append({
                        "section": sec_num,
                        "statement": a.get("statement", a.get("name", "")),
                        "confidence": a.get("confidence", a.get("label", "")),
                        "source": a.get("source", a.get("label", "")),
                    })

        if not all_assumptions:
            return ""

        lines = ["## Appendix A: Assumptions Registry\n"]
        lines.append("| Section | Assumption | Confidence | Source |")
        lines.append("|---------|-----------|------------|--------|")
        for a in all_assumptions:
            stmt = a["statement"][:80]
            lines.append(f"| {a['section']} | {stmt} | {a['confidence']} | {a['source']} |")

        flagged = [a for a in all_assumptions if a["confidence"] == "low" or a["source"] == "assumed"]
        if flagged:
            lines.append(f"\n**{len(flagged)} assumptions require validation before external use.**")

        return "\n".join(lines)

    def _compile_council_appendix(self, council_reports: list) -> str:
        """Compile Council review results into a transparency appendix."""
        lines = ["## Appendix C: Quality Assurance (Council Review)\n"]

        if not council_reports:
            lines.append("No council reviews recorded for this run.")
            return "\n".join(lines)

        lines.append("| Section | Score | Decision | Attempts | Key Finding |")
        lines.append("|---------|-------|----------|----------|-------------|")

        total_score = 0.0
        revisions_triggered = 0

        for report in council_reports:
            section = report.get("section_number", "?")
            score = report.get("score", 0)
            decision = report.get("decision", "?")
            attempt = report.get("attempt", 1)
            critiques = report.get("critiques", [])
            total_score += score
            if decision == "revise":
                revisions_triggered += 1

            key_finding = ""
            critical = [c for c in critiques if c.get("severity") == "critical"]
            if critical:
                key_finding = critical[0].get("top_finding", "")[:60]
            elif critiques:
                key_finding = critiques[0].get("top_finding", "")[:60]

            lines.append(f"| {section} | {score:.1f}/10 | {decision} | {attempt} | {key_finding} |")

        avg_score = total_score / max(len(council_reports), 1)
        lines.append(f"\n**Average Quality Score:** {avg_score:.1f}/10")
        lines.append(f"**Revisions Triggered:** {revisions_triggered}")
        lines.append(f"**Sections Reviewed:** {len(council_reports)}")

        improvements = []
        for report in council_reports:
            for imp in report.get("improvements_made", []):
                improvements.append(f"- [{report.get('section_number', '?')}] {imp}")
        if improvements:
            lines.append("\n**Improvements Made After Review:**")
            lines.extend(improvements[:10])

        return "\n".join(lines)

    def _compile_quality_appendix(self, all_outputs: dict, coherence_audit: Optional[dict]) -> str:
        """Compile data quality and confidence summary."""
        lines = ["## Appendix B: Data Quality & Confidence\n"]

        confidence_counts = {"high": 0, "medium": 0, "low": 0}
        da_verdicts = {"pass": 0, "revise": 0, "reject": 0, "not_reviewed": 0}

        for sec_num, output in all_outputs.items():
            if not isinstance(output, dict):
                continue
            conf = output.get("confidence_score", "medium")
            confidence_counts[conf] = confidence_counts.get(conf, 0) + 1
            verdict = output.get("_da_verdict", "not_reviewed")
            da_verdicts[verdict] = da_verdicts.get(verdict, 0) + 1

        lines.append("**Confidence Distribution:**\n")
        lines.append(f"- High: {confidence_counts['high']} sections")
        lines.append(f"- Medium: {confidence_counts['medium']} sections")
        lines.append(f"- Low: {confidence_counts['low']} sections")

        lines.append("\n**Quality Review (Devil's Advocate):**\n")
        lines.append(f"- Passed: {da_verdicts['pass']}")
        lines.append(f"- Revised: {da_verdicts['revise']}")
        lines.append(f"- Rejected: {da_verdicts['reject']}")
        lines.append(f"- Not reviewed: {da_verdicts['not_reviewed']}")

        if coherence_audit and isinstance(coherence_audit, dict):
            issues = coherence_audit.get("issues", [])
            overall = coherence_audit.get("overall_plan_confidence", "unknown")
            lines.append(f"\n**Coherence Audit:** {len(issues)} issues found, overall confidence: {overall}")
            if issues:
                for issue in issues[:5]:
                    lines.append(f"- [{issue.get('severity', '')}] {issue.get('description', '')}")

        return "\n".join(lines)
